### ISSUE TITLE
Opdracht 11

### ISSUE THREAD

**Issue by GlennvanWezel** [maximegheraille/MI2#1]
Maak een html pagina waarop 3 img tags staan, zorgt ervoor dat er ook een button aanwezig is , en bij elke druk op de knop veranderen de fotos van volgorde.

**Comment by ophalvens** [comment]
ok

**Comment by maximegheraille** [comment]
https://github.com/maximegheraille/MI2/blob/master/Opdrachten/opdracht_11.html
